buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

/*
 * FORCE JAVA 17 ONLY (SAFE FOR CAPACITOR)
 */
subprojects {
    tasks.withType(JavaCompile).configureEach {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

/*
 * CLEAN TASK
 */
task clean(type: Delete) {
    delete rootProject.buildDir
}
