name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # FORCE NODE 22 FIRST (VERY IMPORTANT)
      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Verify Node Version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      - name: Install Capacitor Core
        run: npm install @capacitor/core

      - name: Sync Capacitor Android
        run: npx cap sync android

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kindle-pro-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
